---
common_lang: "en_US.UTF-8"
common_lc_all: "en_US.UTF-8"

timezone: "Asia/Shanghai"

force_update_yum: no

# Define a custom list of packages to install. This won't override the default
# __system_packages
system_packages: []

env: vagrant
